== iOS

iOS is one of the few keyboard layouts that handle more than one platform.
Additionally, it also requires the `symbols` layers.

```
iOS:
  config:
    spellerPackageKey: https://pahkat.uit.no/main/packages/speller-sme?platform=mobile
    spellerPath: se.bhfst
  primary:
    layers:
      default: |
        á š e r t y u i o p ŋ
        a s d f g h j k l đ ŧ
        \s{shift:1.25} \s{spacer:0.25} ž z č c v b n m \s{spacer:0.25} \s{backspace:1.25}
      shift: |
        Á Š E R T Y U I O P Ŋ
        A S D F G H J K L Đ Ŧ
        \s{shift:1.25} \s{spacer:0.25} Ž Z Č C V B N M \s{spacer:0.25} \s{backspace:1.25}
      symbols-1: |
        1 2 3 4 5 6 7 8 9 0
        - / : ; ( ) kr & @ "
        \s{shiftSymbols} \s{spacer:0.25} . , ? ! ' \s{spacer:0.25} \s{backspace}
      symbols-2: |
        [ ] { } # % ^ * + =
        _ \ | ~ < > € $ £ •
        \s{shiftSymbols} \s{spacer:0.25} . , ? ! ' \s{spacer:0.25} \s{backspace}
      
  iPad-9in:
    layers:
      default: |
        \s{"`":0.75}  á š e r t y u i o p ŋ \s{backspace:1.25}
        \s{shift}     a s d f g h j k l đ ŧ \s{shift}
          \s{spacer:0.5}  ž z č c v b n m , . \s{spacer:0.5} \s{return:2}
      shift: |
        \s{"@":0.75}  Á Š E R T Y U I O P Ŋ \s{backspace:1.25}
        \s{shift}     A S D F G H J K L Đ Ŧ \s{shift}
        \s{spacer:0.5}  Ž Z Č C V B N M ! ? \s{spacer:0.5} \s{return:2}
      alt: |
        \s{"@":0.75}  1 2 3  4 5 6 7 8 9 0 å \s{backspace:1.25}
        \s{shift}     % # kr & * ( ) ' " ø æ \s{shift}
        \s{spacer:0.5}  q w  x - = / ; : ! ? \s{spacer:0.5} \s{return:2}
      alt+shift: |
        \s{"@":0.75}  1 2 3  4 5 6 7 8 9 0 Å \s{backspace:1.25}
        \s{shift}     % # kr & * ( ) ' " Ø Æ \s{shift}
        \s{spacer:0.5}  Q W  X - = / ; : ! ? \s{spacer:0.5} \s{return:2}
      symbols-1: |
        \s{spacer:0.75} 1 2 3 4 5 6 7 8 9 0 ` \s{backspace:1.25}
        \s{shiftSymbols} @ # kr & * ( ) ' " + • \s{shiftSymbols}
        \s{spacer:1.5} % _ - = / ; : , . \s{spacer:0.5} \s{return:2}
      symbols-2: |
        \s{spacer:0.75}  1 2 3 4 5 6 7 8 9 0 ´ \s{backspace:1.25}
        \s{shiftSymbols} € $ £ ^ [ ] { } — ° … \s{shiftSymbols}
        \s{spacer:1.5}    § | ~ ≠ \ < > ! ?    \s{spacer:0.5} \s{return:2}
    
  iPad-12in:
    layers:
      ...
```

=== Longpress
A longpress section like this is also needed for alternative keys but isn't specifically exclusive to iOS but rather defined independently in the layout file and shared between Android and iOS
```
  longpress:
    A: Å Æ Ä   À Â Ã Ā Ạ
    Á: Q
    E: Ë É È Ê Ẽ Ē Ẹ Ė Ǝ
    I: Ï Í Ì Î Ĩ Ī Ị I
    ...
```

=== Config
The `config` section is used by Pahkat for spellchecking, the fields:

* `spellerPackageKey` - defines the url for the spellchecking files of the layout we want to generate
* `spellerPath` - defines which spellchecker file to use.
* `space` - name of space key
* `r#return` - name of return key

=== Platforms
Three platforms are supported, all of which have to be defined, `primary`, `iPad-9in`, `iPad-12in`.
```
iPad-9in:
    layers:
      default: |
        ...
```

=== Layers
iOS supports some standard keyboard layers in addition to `symbols-1` and `symbols-2`. 

Each layer is split by line,
typically to 3 lines of the keyboard. 

Special keys need to be preceeded by `\s`,
and is sometimes followed by a number after `:` representing the desired width of the key (keywidth is 1
 by default, centered):

* `\s{spacer:0.5}` - not a key, just a spacer
* `\s{shift}` - Shift
* `\s{backspace:1.25}` - Delete
* `\s{return:2}` - Enter
* `\s{"@":0.75}` - a given key, but with a custom width
* `\s{shiftSymbols}` - switch between symbols-1 and symbols-2 layers
