== Windows
Generating a Windows keyboard layout in the current implementation of `kbdgen` mainly
concerns the generation of .klc files, and then subsequent building of those files
on a Windows system.

KLC is Windows's format for keyboard layouts, meaning Keyboard
Layout Creator, which is also the tool that can be used to view and modify
.klc files. The tool can be downloaded from Microsoft:
https://www.microsoft.com/en-us/download/details.aspx?id=102134

Installing MSKLC requires enabling .NET Framework 3.5 in Windows Programs and Features.

\.klc is a format that has specific requirements for how a keyboard is described and
must be encoded as UTF-16, with Windows style CRLF, or the file will be perceived
as invalid.

For details on the .klc format, please see the developer documentation.

=== Target configuration
A Windows target file does not have to be specified. ??

=== Keyboard layouts

```
windows:
  config:
    locale: se-Latn-FI
  primary:
    layers:
      default: |
        § 1 2 3 4 5 6 7 8 9 0 + ´
          á š e r t y u i o p å ŋ
          a s d f g h j k l ö ä đ
        ž z č c v b n m , . -
      shift: |
        ½ ! " # ¤ % & / ( ) = ? `
          Á Š E R T Y U I O P Å Ŋ
          A S D F G H J K L Ö Ä Đ
        Ž Z Č C V B N M ; : _
      caps: |
        § 1 2 3 4 5 6 7 8 9 0 + ´
          Á Š E R T Y U I O P Å Ŋ
          A S D F G H J K L Ö Ä Đ
        Ž Z Č C V B N M , . -
      caps+shift: |
        ½ ! " # ¤ % & / ( ) = ? `
          á š e r t y u i o p å ŋ
          a s d f g h j k l ö ä đ
        ž z č c v b n m ; : _
      alt: |
        |     \u{0} @     £     $     €     \u{0} {     [     ]     }     \     \u{0}
              q     w     €     \u{0} ŧ     \u{0} \u{0} ï     õ     \u{0} ¨     ~
              â     \u{0} \u{0} \u{0} ǧ     ǥ     \u{0} ǩ     \u{0} ø     æ     '
        ǯ     ʒ     x     \u{0} \u{0} \u{0} \u{0} µ     <     >     \u{0}
      alt+shift: |
        \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
              Q     W     \u{0} \u{0} Ŧ     \u{0} \u{0} Ï     Õ     \u{0} ^     ˇ
              Â     \u{0} \u{0} \u{0} Ǧ     Ǥ     \u{0} Ǩ     \u{0} Ø     Æ     *
        Ǯ     Ʒ     X     \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
      ctrl: |
        \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
        \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
        \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
        \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0} \u{0}
  deadKeys:
    default: [´]
    shift: ['`']
    caps: [´]
    caps+shift: ['`']
    alt: ['~', ¨]
    alt+shift: [^, ˇ]
```

==== Config
The `config` section is used by Pahkat for spellchecking, the fields:

* `locale` - defines the language locale
* `id` - defines the id

==== Layers
Each layer is split by line,
typically to 3 lines of the keyboard. Keys in the format of \u{} are written in Unicode to avoid display issues. In particular, \u{0} is an absent key. Note that KLC cannot support keys outside the Basic Multilingual Plane, even if Unicode supports them.
