//! Export, kbdgen's extension elements, the LDML-only view, layout data in
//! referenced documents, and engine behaviour of a dead-key keyboard.

use kbd_engine::harness::Harness;
use kbd_engine::{Gesture, Key as EKey, KeyEvent, ModifierState};
use kbd_model::{
    BottomRow, Component, ExtraModifierKey, Host, ModifierSet, Modifiers, Role, Text, TransformList,
};

use super::*;
use crate::{ComposeValue, Extensions, LayoutData, export, replace_extensions, write};

/// A keyboard in the form v4 lowering produces: dead keys as markers with
/// compose, fallback and backspace groups, and every kbdgen extension.
const DEAD_KEYS: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<keyboard3 locale="sme" conformsTo="45" xmlns="https://schemas.unicode.org/cldr/45/keyboard3"
    xmlns:kbdgen="https://divvun.no/ns/kbdgen-ldml/1">
  <info name="Davvisámegiella" />
  <settings normalization="disabled" />
  <displays>
    <display output="\m{dk_00B4}" display="´" />
    <display keyId="space" display="space" />
  </displays>
  <keys>
    <key id="dk-dk_00B4" output="\m{dk_00B4}" />
    <key id="u-00E1" output="á" />
    <key id="shift" layerId="shift" />
    <key id="bksp" gap="true" />
    <key id="a" output="a" longPressKeyIds="u-00E1" />
    <key id="to-shift" layerId="shift" />
    <special>
      <kbdgen:role keyId="shift" role="shift" />
      <kbdgen:role keyId="bksp" role="backspace" />
    </special>
  </keys>
  <layers formId="iso">
    <layer modifiers="none">
      <row keys="dk-dk_00B4" />
      <row keys="q w e" />
      <row keys="a s d" />
    </layer>
    <layer modifiers="shift">
      <row keys="dk-dk_00B4" />
      <row keys="Q W E" />
      <row keys="A S D" />
    </layer>
    <special>
      <kbdgen:extraModifier key="capsLock" />
      <kbdgen:layer modifiers="cmd">
        <kbdgen:row keys="dk-dk_00B4" />
        <kbdgen:row keys="q w e" />
      </kbdgen:layer>
      <kbdgen:layer id="x1" modifiers="extra1">
        <kbdgen:row keys="u-00E1" />
      </kbdgen:layer>
    </special>
  </layers>
  <layers formId="touch">
    <layer id="base">
      <row keys="q w e" />
      <row keys="shift a bksp" />
    </layer>
    <layer id="shift">
      <row keys="Q W E" />
      <row keys="shift A bksp" />
    </layer>
    <special>
      <kbdgen:touchSet name="phone" bottomRow="host" />
    </special>
  </layers>
  <transforms type="simple">
    <transformGroup>
      <transform from="\m{dk_00B4}a" to="á" />
      <transform from="\m{dk_00B4}\u{0020}" to="´" />
      <special><kbdgen:generated by="deadKeys-compose" /></special>
    </transformGroup>
    <transformGroup>
      <transform from="\m{dk_00B4}\m{dk_00B4}" to="´\m{dk_00B4}" />
      <transform from="\m{dk_00B4}(.)" to="´$1" />
      <special><kbdgen:generated by="deadKeys-fallback" /></special>
    </transformGroup>
  </transforms>
  <transforms type="backspace">
    <transformGroup>
      <transform from="\m{.}" />
      <special><kbdgen:generated by="deadKeys-backspace" /></special>
    </transformGroup>
  </transforms>
  <special>
    <kbdgen:keyboard tag="sme" host="windows" decimal="," spaceLabel="space" returnLabel="enter" impliedLayers="macOS" />
    <kbdgen:displayName lang="sme" name="Davvisámegiella" />
    <kbdgen:displayName lang="en" name="Northern Sami" />
    <kbdgen:flush marker="dk_00B4" output="´" />
    <kbdgen:deadKeyName marker="dk_00B4" name="ACUTE" />
    <kbdgen:windows shiftLock="true" />
    <kbdgen:windowsKeyName key="Caps Lock" name="Bokstavlås" />
    <kbdgen:target host="windows" name="locale" value="se-NO" />
    <kbdgen:deadKey identity="´" marker="dk_00B4" display="´" standalone="´" name="ACUTE">
      <kbdgen:compose input="a" output="á" />
      <kbdgen:compose input="b" marker="dk_00B4-0062" standalone="b">
        <kbdgen:compose input="c" output="ç" />
      </kbdgen:compose>
    </kbdgen:deadKey>
    <other xmlns="urn:example"><kept /></other>
  </special>
</keyboard3>
"#;

// [spec:kbdgen:def:ldml.xml.special+2/test]
#[test]
fn kbdgen_elements_resolve_to_the_superset() {
    let r = resolved(DEAD_KEYS);
    let kb = &r.keyboard;
    assert_eq!(kb.host, Some(Host::Windows));
    assert_eq!(kb.decimal, Some(Text::from(",")));
    assert_eq!(kb.displays.labels.space.as_deref(), Some("space"));
    assert_eq!(kb.displays.labels.r#return.as_deref(), Some("enter"));
    assert_eq!(kb.flush.get(&0).map(String::as_str), Some("´"));
    assert_eq!(kb.dead_key_names.get(&0).map(String::as_str), Some("ACUTE"));
    assert!(kb.windows.shift_lock && !kb.windows.lrm_rlm);
    assert_eq!(
        kb.windows.key_names.get("Caps Lock").map(String::as_str),
        Some("Bokstavlås")
    );
    assert_eq!(kb.windows.extra_modifiers, [ExtraModifierKey::CapsLock]);
    let roles: Vec<(&str, Role)> = kb
        .keys
        .iter()
        .filter_map(|k| k.role.map(|r| (k.id.as_str(), r)))
        .collect();
    assert_eq!(roles, [("shift", Role::Shift), ("bksp", Role::Backspace)]);
    let hw = kb.hardware.as_ref().unwrap();
    assert_eq!(hw.layers.len(), 4, "kbdgen layers follow the LDML ones");
    assert!(hw.layers[2].is_native());
    assert_eq!(hw.layers[3].id.as_deref(), Some("x1"));
    assert_eq!(
        hw.layers[3].modifiers,
        [ModifierSet::Set(Modifiers::of(&[Component::Extra1]))]
    );
    assert_eq!(kb.touch[0].name.as_deref(), Some("phone"));
    assert_eq!(kb.touch[0].bottom_row, BottomRow::Host);
    let ext = &r.extensions;
    assert_eq!(ext.tag.as_deref(), Some("sme"));
    assert_eq!(ext.implied_layers.as_deref(), Some("macOS"));
    assert_eq!(ext.display_names.len(), 2);
    assert_eq!(ext.targets[0].value, "se-NO");
    assert_eq!(ext.generated.len(), 3);
    assert_eq!(
        (ext.generated[2].list, ext.generated[2].group),
        (TransformList::Backspace, 0)
    );
    let dk = &ext.dead_keys[0];
    assert_eq!(
        (dk.identity.as_str(), dk.name.as_deref()),
        ("´", Some("ACUTE"))
    );
    assert!(
        matches!(&dk.compose[1].value, ComposeValue::Node { compose, .. } if compose.len() == 1)
    );
}

// [spec:kbdgen:def:ldml.xml.special+2/test]
#[test]
fn unknown_kbdgen_content_is_an_error() {
    let cases = [
        (
            "<kbdgen:keyboard tag=\"sme\"",
            "<kbdgen:keyboard bogus=\"1\" tag=\"sme\"",
            "unknown attribute",
        ),
        (
            "<kbdgen:windows shiftLock=\"true\" />",
            "<kbdgen:nonsense />",
            "not a kbdgen element",
        ),
        (
            "<kbdgen:windows shiftLock=\"true\" />",
            "<kbdgen:windows shiftLock=\"yes\" />",
            "not true or false",
        ),
        ("role=\"backspace\"", "role=\"delete\"", "unknown role"),
        (
            "bottomRow=\"host\"",
            "bottomRow=\"device\"",
            "not host or authored",
        ),
        ("key=\"capsLock\"", "key=\"leftAlt\"", "not rightCtrl"),
        ("host=\"windows\"", "host=\"amiga\"", "unknown host"),
    ];
    for (from, to, needle) in cases {
        let err = resolve_error(&DEAD_KEYS.replace(from, to));
        assert!(err.contains(needle), "{to}: {err}");
    }
}

// [spec:kbdgen:thm:ldml.xml.superset-roundtrip/test]
#[test]
fn exported_superset_resolves_to_the_same_model() {
    let r = resolved(DEAD_KEYS);
    let xml = write(&export(&r.keyboard, &r.extensions));
    let again = resolved(&xml);
    assert_eq!(again.keyboard, r.keyboard);
    assert_eq!(again.extensions, r.extensions);
    assert_eq!(
        write(&export(&again.keyboard, &again.extensions)),
        xml,
        "export is deterministic"
    );
}

/// Removes every element in kbdgen's namespace, as an LDML-only consumer
/// sees the document, keeping the `special` elements themselves.
fn ldml_only(xml: &str) -> String {
    let mut doc = read_keyboard("view.xml", None, xml.as_bytes())
        .unwrap()
        .document;
    let mut stack = vec![doc.root()];
    while let Some(el) = stack.pop() {
        for child in el.children(&doc) {
            if child.prefix(&doc) == Some("kbdgen") {
                el.remove_child(&mut doc, child.as_node());
            } else {
                stack.push(child);
            }
        }
    }
    write(&doc)
}

// [spec:kbdgen:sem:ldml.xml.ldml-view+1/test]
#[test]
fn ldml_only_consumer_sees_plain_ldml() {
    let r = resolved(DEAD_KEYS);
    let view = resolved(&ldml_only(&write(&export(&r.keyboard, &r.extensions)))).keyboard;
    let hw = view.hardware.as_ref().unwrap();
    assert_eq!(hw.layers.len(), 2, "no native-only or extra layers");
    assert!(view.keys.iter().all(|k| k.role.is_none()));
    let shift = view.key(view.key_index("shift").unwrap()).unwrap();
    assert_eq!(
        shift.layer_id.as_deref(),
        Some("shift"),
        "a role key is a layer switch"
    );
    assert!(
        view.key(view.key_index("bksp").unwrap()).unwrap().gap,
        "or a gap"
    );
    assert!(view.flush.is_empty() && view.decimal.is_none() && view.host.is_none());
    assert!(!view.windows.shift_lock && view.windows.extra_modifiers.is_empty());
    assert_eq!(
        view.simple, r.keyboard.simple,
        "the generated dead-key groups stay"
    );
    assert_eq!(view.backspace, r.keyboard.backspace);
    assert_eq!(view.displays.entries, r.keyboard.displays.entries);
    assert_eq!(view.displays.labels.space, None);
    assert_eq!(view.touch[0].bottom_row, BottomRow::Authored);
}

// [spec:kbdgen:req:ldml.xml.export+1/test]
#[test]
fn export_follows_dtd_order_and_forms() {
    let xml = keyboard(
        "",
        r#"<keys><key id="wide" output="w" width="1.250"/><key id="mark" output="\u{301}"/></keys>
           <layers formId="iso"><layer modifiers="shift caps, none"><row keys="wide mark a"/></layer></layers>
           <variables><string id="unused" value="x"/></variables>
           <transforms type="simple"><transformGroup><transform from="a\.(b)" to="$$\\$1"/></transformGroup></transforms>"#,
    )
    .replace("<info name=\"Test\"/>", "<info name=\"Test\" attribution=\"CC\" author=\"A\"/>");
    let r = resolved(&xml);
    let out = write(&export(&r.keyboard, &r.extensions));
    let expected = r#"<?xml version="1.0" encoding="utf-8"?>
<keyboard3 locale="sme" conformsTo="47" xmlns="https://schemas.unicode.org/cldr/47/keyboard3">
  <info name="Test" author="A" attribution="CC" />
  <keys>
    <key id="wide" output="w" width="1.25" />
    <key id="mark" output="\u{0301}" />
  </keys>
  <layers formId="iso">
    <layer modifiers="none, caps shift">
      <row keys="wide mark a" />
    </layer>
  </layers>
  <transforms type="simple">
    <transformGroup>
      <transform from="a\.(b)" to="$$\\$1" />
    </transformGroup>
  </transforms>
</keyboard3>
"#;
    assert_eq!(out, expected);
    let custom = resolved(&keyboard(
        "",
        r#"<forms><form id="mine"><scanCodes codes="1E 30"/></form></forms>
           <layers formId="mine"><layer modifiers="none"><row keys="a b"/></layer></layers>"#,
    ));
    let out = write(&export(&custom.keyboard, &custom.extensions));
    assert!(
        out.contains("<form id=\"mine\">\n      <scanCodes codes=\"1E 30\" />"),
        "{out}"
    );
}

const REFERENCED: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- authored by hand -->
<keyboard3 locale="sme" conformsTo="45" xmlns:k="https://divvun.no/ns/kbdgen-ldml/1">
  <info name="T" />
  <layers formId="iso">
    <layer modifiers="none"><row keys="a" /></layer>
  </layers>
  <special>
    <!-- keep me -->
    <k:keyboard tag="old" impliedLayers="none" />
    <k:displayName lang="sme" name="Old" />
    <k:flush marker="m" output="x" />
    <other xmlns="urn:example" />
  </special>
</keyboard3>
"#;

// [spec:kbdgen:req:ldml.xml.ldml-ref+2/test]
#[test]
fn layout_data_replaces_only_layout_elements() {
    let mut doc = read_keyboard("ref.xml", None, REFERENCED.as_bytes())
        .unwrap()
        .document;
    let data = LayoutData {
        tag: Some("sme".into()),
        host: Some(Host::MacOs),
        decimal: Some(",".into()),
        display_names: [("sme".to_string(), "Davvisámegiella".to_string())].into(),
        ..LayoutData::default()
    };
    replace_extensions(&mut doc, &data);
    let out = write(&doc);
    assert!(out.contains("<!-- authored by hand -->") && out.contains("<!-- keep me -->"));
    assert!(out.contains("<k:flush marker=\"m\" output=\"x\" />"));
    assert!(out.contains("<other xmlns=\"urn:example\" />"));
    assert!(
        out.contains(r#"<k:keyboard tag="sme" host="macOS" decimal="," impliedLayers="none" />"#),
        "{out}"
    );
    assert!(out.contains(r#"<k:displayName lang="sme" name="Davvisámegiella" />"#));
    assert!(!out.contains("Old") && !out.contains("tag=\"old\""));
    let r = resolved(&out);
    assert_eq!(r.keyboard.host, Some(Host::MacOs));
    assert_eq!(r.extensions.tag.as_deref(), Some("sme"));

    let mut bare = read_keyboard("bare.xml", None, MINIMAL_BARE.as_bytes())
        .unwrap()
        .document;
    replace_extensions(&mut bare, &data);
    let out = write(&bare);
    assert!(
        out.contains("xmlns:kbdgen1=\"https://divvun.no/ns/kbdgen-ldml/1\""),
        "{out}"
    );
    assert!(
        out.contains("<special>\n    <kbdgen1:keyboard tag=\"sme\""),
        "{out}"
    );
}

const MINIMAL_BARE: &str = r#"<keyboard3 locale="sme" conformsTo="45" xmlns:kbdgen="urn:other"><info name="T"/><layers formId="iso"/></keyboard3>"#;

fn scan(h: &mut Harness, code: u8, modifiers: ModifierState) -> bool {
    h.send(&KeyEvent::with(EKey::Scan(code), modifiers));
    h.passed()
}

fn id(h: &mut Harness, id: &str, gesture: Gesture) -> bool {
    h.send(&KeyEvent::new(EKey::Id {
        id: id.to_string(),
        gesture,
    }));
    h.passed()
}

// [spec:kbdgen:sem:ldml.xml.resolve+1/test]
#[test]
fn dead_keys_compose_fall_back_and_cancel() {
    let m = engine(resolved(DEAD_KEYS).keyboard);
    let mut s = Harness::new(&m);
    scan(&mut s, 0x29, ModifierState::default());
    assert_eq!(
        (s.document(), s.preedit()),
        ("", "´"),
        "a pending dead key shows its flush"
    );
    scan(&mut s, 0x1E, ModifierState::default());
    assert_eq!(s.document(), "á");
    scan(&mut s, 0x29, ModifierState::default());
    scan(&mut s, 0x1F, ModifierState::default());
    assert_eq!(s.document(), "á´s", "unmatched: standalone, then the key");
    scan(&mut s, 0x29, ModifierState::shift());
    s.send(&KeyEvent::new(EKey::Backspace));
    assert_eq!(
        (s.document(), s.preedit()),
        ("á´s", ""),
        "backspace cancels only the dead key"
    );
    let mut s = Harness::new(&m);
    assert!(scan(
        &mut s,
        0x10,
        ModifierState {
            cmd: true,
            ..ModifierState::default()
        }
    ));
}

// [spec:kbdgen:sem:ldml.xml.resolve+1/test]
#[test]
fn touch_roles_and_long_press_drive_engine() {
    let m = engine(resolved(DEAD_KEYS).keyboard);
    let mut s = Harness::new(&m);
    let touch = |s: &mut Harness, layer: usize, row: usize, col: usize, gesture: Gesture| {
        s.send(&KeyEvent::new(EKey::Touch {
            set: 0,
            layer,
            row,
            col,
            gesture,
        }));
        s.passed()
    };
    assert!(
        touch(&mut s, 0, 1, 0, Gesture::Tap),
        "role keys are the host's own"
    );
    assert!(!touch(&mut s, 0, 1, 1, Gesture::LongPress(1)));
    assert_eq!(s.document(), "á");
    assert!(
        id(&mut s, "shift", Gesture::Tap),
        "the host switches layers for a role key"
    );
    assert!(!id(&mut s, "to-shift", Gesture::Tap));
    assert_eq!(s.layer(), Some("shift"));
    id(&mut s, "a", Gesture::LongPress(1));
    assert_eq!(s.document(), "áá");
    assert!(id(&mut s, "bksp", Gesture::Tap), "a gap key passes");
}

#[test]
fn extensions_default_is_empty() {
    let r = resolved(&keyboard("", r#"<layers formId="iso"/>"#));
    assert_eq!(r.extensions, Extensions::default());
    let out = write(&export(&r.keyboard, &r.extensions));
    assert!(!out.contains("kbdgen"), "{out}");
    assert!(!out.contains("<keys>"), "implied keys are left out");
    assert!(!out.contains("<forms>"), "implied forms are left out");
}

// [spec:kbdgen:def:ldml.xml.document/test]
#[test]
fn kbdgen_elements_are_found_by_namespace_uri() {
    let foreign = REFERENCED.replace("https://divvun.no/ns/kbdgen-ldml/1", "urn:not-kbdgen");
    let r = resolved(&foreign);
    assert_eq!(
        r.extensions.tag, None,
        "a prefix bound to another URI is not kbdgen's"
    );
    assert_eq!(resolved(REFERENCED).extensions.tag.as_deref(), Some("old"));
    let mut doc = read_keyboard("h.xml", None, MINIMAL_BARE.as_bytes())
        .unwrap()
        .document;
    crate::set_host(&mut doc, Host::Ios);
    crate::set_host(&mut doc, Host::Android);
    let out = write(&doc);
    assert_eq!(out.matches("host=").count(), 1, "{out}");
    assert_eq!(resolved(&out).keyboard.host, Some(Host::Android));
}
