//! kbdgen's extension elements (`ldml.xml.special`): the namespace, the
//! data that lies outside the model, and reading the elements.

use std::collections::BTreeMap;

use kbd_model::TransformList;

use crate::diag::Result;
use crate::escape::decode_plain;
use crate::tree::El;

// [spec:kbdgen:def:ldml.xml.special+1]
/// The namespace of kbdgen's extension elements.
pub const KBDGEN_NS: &str = "https://divvun.no/ns/kbdgen-ldml/1";

/// The prefix exported documents bind [`KBDGEN_NS`] to.
pub const KBDGEN_PREFIX: &str = "kbdgen";

/// A layout's own platform setting (`ldml.yaml.targets`), carried as
/// `kbdgen:target`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Target {
    pub host: String,
    pub name: String,
    pub value: String,
}

/// What a `compose` entry of a dead key leads to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ComposeValue {
    Output(String),
    Node {
        marker: String,
        standalone: String,
        compose: Vec<Compose>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Compose {
    pub input: String,
    pub value: ComposeValue,
}

/// A v4 `deadKeys` entry, as authoring metadata (`ldml.yaml.import`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeadKey {
    pub identity: String,
    pub marker: String,
    pub display: String,
    pub standalone: String,
    pub name: Option<String>,
    pub compose: Vec<Compose>,
}

/// A transform group generated by v4 lowering, marked `kbdgen:generated`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    pub list: TransformList,
    /// The group's index in its list.
    pub group: usize,
    /// `deadKeys-compose`, `deadKeys-fallback` or `deadKeys-backspace`.
    pub by: String,
}

// [spec:kbdgen:def:ldml.xml.special+1]
/// The kbdgen data of a document that is not part of the keyboard model:
/// layout-level fields and authoring metadata. Resolution reads it and
/// export writes it; it never changes the model.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Extensions {
    /// `kbdgen:keyboard@tag`, the layout tag.
    pub tag: Option<String>,
    /// `kbdgen:keyboard@impliedLayers`.
    pub implied_layers: Option<String>,
    pub display_names: BTreeMap<String, String>,
    pub targets: Vec<Target>,
    pub dead_keys: Vec<DeadKey>,
    pub generated: Vec<Generated>,
}

// [spec:kbdgen:def:ldml.xml.document]
/// The prefix bound to [`KBDGEN_NS`] on the root, if any.
pub(crate) fn kbdgen_prefix(root: &El) -> Option<String> {
    root.attrs.iter().find_map(|(k, v)| {
        (v == KBDGEN_NS)
            .then(|| k.strip_prefix("xmlns:").map(str::to_string))
            .flatten()
    })
}

/// The kbdgen elements in `el`'s `special` children, in document order.
pub(crate) fn kbdgen_children<'a>(el: &'a El, prefix: Option<&'a str>) -> Vec<&'a El> {
    let Some(prefix) = prefix else {
        return Vec::new();
    };
    el.children_named("special")
        .flat_map(|s| s.children.iter())
        .filter(|c| c.prefix.as_deref() == Some(prefix))
        .collect()
}

/// Checks that a kbdgen element has only the attributes `allowed`, and the
/// `required` ones among them.
pub(crate) fn check_attrs(el: &El, allowed: &[&str], required: &[&str]) -> Result<()> {
    for (k, _) in &el.attrs {
        if !allowed.contains(&k.as_str()) {
            return Err(el.attr_error(k, format!("unknown attribute of {}", el.qualified())));
        }
    }
    for r in required {
        if el.attr(r).is_none() {
            return Err(el.attr_error(r, "required attribute is missing"));
        }
    }
    Ok(())
}

/// A required attribute, escape-decoded.
pub(crate) fn plain_attr(el: &El, name: &str) -> Result<String> {
    let value = el.attr(name).unwrap_or("");
    decode_plain(value).map_err(|e| el.attr_error(name, e.to_string()))
}

pub(crate) fn bool_attr(el: &El, name: &str) -> Result<bool> {
    match el.attr(name) {
        None | Some("false") => Ok(false),
        Some("true") => Ok(true),
        Some(other) => Err(el.attr_error(name, format!("{other:?} is not true or false"))),
    }
}

fn read_compose(el: &El, prefix: &str) -> Result<Compose> {
    if el.prefix.as_deref() != Some(prefix) || el.name != "compose" {
        return Err(el.error("a dead key holds only kbdgen:compose elements"));
    }
    let input = plain_attr(el, "input")?;
    let value = if el.attr("output").is_some() {
        check_attrs(el, &["input", "output"], &["input", "output"])?;
        if !el.children.is_empty() {
            return Err(el.error("a compose with output has no children"));
        }
        ComposeValue::Output(plain_attr(el, "output")?)
    } else {
        check_attrs(
            el,
            &["input", "marker", "standalone"],
            &["input", "marker", "standalone"],
        )?;
        ComposeValue::Node {
            marker: plain_attr(el, "marker")?,
            standalone: plain_attr(el, "standalone")?,
            compose: el
                .children
                .iter()
                .map(|c| read_compose(c, prefix))
                .collect::<Result<_>>()?,
        }
    };
    Ok(Compose { input, value })
}

/// Reads a `kbdgen:deadKey`.
pub(crate) fn read_dead_key(el: &El, prefix: &str) -> Result<DeadKey> {
    check_attrs(
        el,
        &["identity", "marker", "display", "standalone", "name"],
        &["identity", "marker", "display", "standalone"],
    )?;
    Ok(DeadKey {
        identity: plain_attr(el, "identity")?,
        marker: plain_attr(el, "marker")?,
        display: plain_attr(el, "display")?,
        standalone: plain_attr(el, "standalone")?,
        name: match el.attr("name") {
            Some(_) => Some(plain_attr(el, "name")?),
            None => None,
        },
        compose: el
            .children
            .iter()
            .map(|c| read_compose(c, prefix))
            .collect::<Result<_>>()?,
    })
}
